plugins {
    id 'maven-publish'
}


publishing {
    publications {
        maven(MavenPublication) {
            groupId = 'au.com.permeance.liferay'
            artifactId = 'liferay-scripting-helper-portlet'
            version = '1.0.0'

            from components.java
        }
    }
}


dependencies {

	compileOnly group: "com.liferay.portal", name: "release.dxp.api"

	cssBuilder group: "com.liferay", name: "com.liferay.css.builder", version: "3.1.4"

	implementation("org.apache.commons:commons-fileupload2-core:2.0.0-M5")

	implementation("org.apache.commons:commons-fileupload2-jakarta-servlet6:2.0.0-M5")

	implementation("org.apache.commons:commons-fileupload2-portlet:2.0.0-M5")

	implementation("commons-io:commons-io:2.22.0")

}

