<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>au.com.permeance.liferay</groupId>
	<artifactId>liferay-scripting-helper-portlet</artifactId>
	<version>7.4.13.0</version>
	<developers>
		<developer>
			<id>chun-ho</id>
			<name>Chun Ho</name>
			<email>chun.ho@permeance.com.au</email>
			<organization>Permeance Technologies</organization>
			<organizationUrl>https://www.permeance.com.au</organizationUrl>
			<roles>
				<role>Project creator</role>
			</roles>
			<timezone>+8</timezone>
		</developer>
		<developer>
			<id>terry-mueller</id>
			<name>Terry Mueller</name>
			<email>terry.mueller@permeance.com.au</email>
			<organization>Permeance Technologies</organization>
			<organizationUrl>https://www.permeance.com.au</organizationUrl>
			<roles>
				<role>Project developer</role>
			</roles>
			<timezone>+8</timezone>
		</developer>
		<developer>
			<id>gerry-hale</id>
			<name>Gerry Hale</name>
			<email>gerard.hale@permeance.com.au</email>
			<organization>Permeance Technologies</organization>
			<organizationUrl>https://www.permeance.com.au</organizationUrl>
			<roles>
				<role>Project developer</role>
			</roles>
			<timezone>+8</timezone>
		</developer>
		<developer>
			<id>tim-telcik</id>
			<name>Tim Telcik</name>
			<email>telcik@gmail.com</email>
			<roles>
				<role>Project developer</role>
			</roles>
			<timezone>+8</timezone>
		</developer>
	</developers>
	<scm>
		<connection>scm:git:https://github.com/permeance/liferay-scripting-helper.git</connection>
		<developerConnection>scm:git:https://github.com/permeance/liferay-scripting-helper.git</developerConnection>
		<url>https://github.com/permeance/liferay-scripting-helper</url>
	  <tag>HEAD</tag>
	</scm>
	<distributionManagement>
		<snapshotRepository>
			<id>permeance-snapshots</id>
			<name>Snapshots</name>
			<url>https://repo.permeance.com.au/repository/snapshots/</url>
		</snapshotRepository>
		<repository>
			<id>permeance-releases</id>
			<name>Releases</name>
			<url>https://repo.permeance.com.au/repository/internal/</url>
		</repository>
	</distributionManagement>
	<properties>
		<!-- see LIFERAY_PORTAL_SRC/modules/modules.properties -->
		<biz.aQute.bndlib.version>7.2.3</biz.aQute.bndlib.version>
		<bnd-maven-plugin.version>7.2.3</bnd-maven-plugin.version>
		<commons-io.version>2.22.0</commons-io.version>
		<commons-fileupload2.version>2.0.0-M5</commons-fileupload2.version>
		<commons-fileupload2-core.version>${commons-fileupload2.version}</commons-fileupload2-core.version>
		<commons-fileupload2-jakarta-servlet6.version>${commons-fileupload2.version}</commons-fileupload2-jakarta-servlet6.version>
		<commons-fileupload2-portlet.version>${commons-fileupload2.version}</commons-fileupload2-portlet.version>
		<jakarta.portlet-api.version>4.0.0</jakarta.portlet-api.version>
		<jakarta.servlet-api.version>6.0.0</jakarta.servlet-api.version>
		<jakarta.servlet.jsp.jstl-api.version>3.0.2</jakarta.servlet.jsp.jstl-api.version>
		<jakarta.servlet.jstl.version>3.0.1</jakarta.servlet.jstl.version>
		<jakarta.ws.rs-api.version>4.0.0</jakarta.ws.rs-api.version>
		<jstl.version>1.2</jstl.version>
		<liferay.ant.bnd.version>3.2.16</liferay.ant.bnd.version>
		<liferay.application.list.api.version>14.0.1</liferay.application.list.api.version>
		<liferay.jakarta.portlet-api.version>4.0.0</liferay.jakarta.portlet-api.version>		
		<liferay.petra.string.version>5.3.7</liferay.petra.string.version>
		<liferay.portal.kernel.version>181.1.0</liferay.portal.kernel.version>
		<liferay.util.bridges.version>11.0.0</liferay.util.bridges.version>
		<liferay.util.java.version>22.0.2</liferay.util.java.version>
		<liferay.util.taglib.version>28.0.1</liferay.util.taglib.version>
		<maven-compiler-plugin.version>3.15.0</maven-compiler-plugin.version>
		<maven-jar-plugin.version>3.5.0</maven-jar-plugin.version>
		<osgi.cmpn.version>7.0.0</osgi.cmpn.version>
		<org.osgi.service.component.annotations.version>1.3.0</org.osgi.service.component.annotations.version>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<slf4j.version>2.0.17</slf4j.version>
	</properties>
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>com.liferay.portal</groupId>
				<artifactId>release.dxp.bom.third.party</artifactId>
				<version>2026.q1.5</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
			<dependency>
				<groupId>com.liferay.portal</groupId>
				<artifactId>release.dxp.bom</artifactId>
				<version>2026.q1.5</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
			<dependency>
				<groupId>com.liferay.portal</groupId>
				<artifactId>release.dxp.bom.compile.only</artifactId>
				<version>2026.q1.5</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>
	<dependencies>
		<dependency>
			<groupId>com.liferay</groupId>
			<artifactId>com.liferay.application.list.api</artifactId>
			<version>${liferay.application.list.api.version}</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>com.liferay</groupId>
			<artifactId>com.liferay.petra.string</artifactId>
			<version>${liferay.petra.string.version}</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>com.liferay.jakarta.portlet</groupId>
			<artifactId>com.liferay.jakarta.portlet-api</artifactId>
			<version>${liferay.jakarta.portlet-api.version}</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.liferay.portal</groupId>
			<artifactId>com.liferay.portal.kernel</artifactId>
			<version>${liferay.portal.kernel.version}</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>com.liferay.portal</groupId>
			<artifactId>com.liferay.util.taglib</artifactId>
			<version>${liferay.util.taglib.version}</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-fileupload2-core</artifactId>
			<version>${commons-fileupload2-core.version}</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-fileupload2-jakarta-servlet6</artifactId>
			<version>${commons-fileupload2-jakarta-servlet6.version}</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-fileupload2-portlet</artifactId>
			<version>${commons-fileupload2-portlet.version}</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>commons-io</groupId>
			<artifactId>commons-io</artifactId>
			<version>${commons-io.version}</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>jakarta.servlet</groupId>
			<artifactId>jakarta.servlet-api</artifactId>
			<version>${jakarta.servlet-api.version}</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.osgi</groupId>
			<artifactId>osgi.cmpn</artifactId>
			<version>${osgi.cmpn.version}</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.osgi</groupId>
			<artifactId>org.osgi.service.component.annotations</artifactId>
			<version>${org.osgi.service.component.annotations.version}</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>jcl-over-slf4j</artifactId>
			<version>${slf4j.version}</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
			<version>${slf4j.version}</version>
			<scope>provided</scope>
		</dependency>
	</dependencies>
	<build>
		<finalName>${project.artifactId}</finalName>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>${maven-compiler-plugin.version}</version>
				<configuration>
					<source>21</source>
					<target>21</target>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-jar-plugin</artifactId>
				<version>${maven-jar-plugin.version}</version>
				<configuration>
					<archive>
						<manifestFile>${project.build.outputDirectory}/META-INF/MANIFEST.MF</manifestFile>
					</archive>
					<excludes>
						<exclude>**/META-INF/resources/**/.sass-cache/</exclude>
					</excludes>
				</configuration>
			</plugin>
			<plugin>
				<groupId>biz.aQute.bnd</groupId>
				<artifactId>bnd-maven-plugin</artifactId>
				<version>${bnd-maven-plugin.version}</version>
				<executions>
					<execution>
						<id>default-bnd-process</id>
						<goals>
							<goal>bnd-process</goal>
						</goals>
					</execution>
				</executions>
				<dependencies>
					<dependency>
						<groupId>biz.aQute.bnd</groupId>
						<artifactId>biz.aQute.bndlib</artifactId>
						<version>${biz.aQute.bndlib.version}</version>
					</dependency>
					<dependency>
						<groupId>com.liferay</groupId>
						<artifactId>com.liferay.ant.bnd</artifactId>
						<version>${liferay.ant.bnd.version}</version>
					</dependency>
				</dependencies>
			</plugin>
		</plugins>
	</build>
</project>
